#pragma once
#ifndef DEFINE_MANAGER

#define ZERO 0

#define DIRECTION_UP 3
#define DIRECTION_RIGHT 2
#define DIRECTION_DOWN 0
#define DIRECTION_LEFT 1
#define DIRECTION_NOT_AVAILABLE -1

#define LOG_LEVEL_VERBOSE 0
#define LOG_LEVEL_INFO 1
#define LOG_LEVEL_DEBUG 2
#define LOG_LEVEL_WARN 3
#define LOG_LEVEL_ERROR 4

#define IMAGE_UPDATE_TIME 10
#define PLAYER_MOVE_TIME 20

#endif // !DEFINE_MANAGER
